package com.example.dueldex.core.model.enums

enum class EffectType(val filterName: String) {
    BACK_TO_DECK("Back to Deck"),
    BACK_TO_HAND("Back to Hand"),
    BANISH("Banish"),
    CHANGE_ATK_OR_DEF("Change ATK or DEF"),
    CONTROL("Control"),
    COUNTER("Counter"),
    DAMAGE_LP("Damage LP"),
    DESTROY_MONSTER("Destroy Monster"),
    DIRECT_ATTACK("Direct Attack"),
    DRAW("Draw"),
    EFFECT_DAMAGE("Effect Damage"),
    FUSION_RELATED("Fusion-Related"),
    GAMBLE("Gamble"),
    GRAVEYARD("Graveyard"),
    INCREASE_LEVEL("Increase Level"),
    LINK_RELATED("LINK-Related"),
    NEGATE("Negate"),
    PENDULUM_RELATED("Pendulum-Related"),
    PIERCING("Piercing"),
    RECOVER_LP("Recover LP"),
    REPEAT_ATTACK("Repeat Attack"),
    RITUAL_RELATED("Ritual-Related"),
    SEARCH("Search"),
    SELECT("Select"),
    SELF_BURN("Self Burn"),
    SPECIAL_SUMMON("Special Summon"),
    SYNCHRO_RELATED("Synchro-Related"),
    TOKEN("Token"),
    TUNER_RELATED("Tuner-Related"),
    WIN_THE_DUEL("Win the Duel"),
    XYZ_RELATED("XYZ-Related")
}