package com.example.loldex.core.model.enums

enum class CardType(val filterName: String) {
    EFFECT_MONSTER("Effect Monster"),
    FLIP_EFFECT_MONSTER("Flip Effect Monster"),
    FUSION_MONSTER("Fusion Monster"),
    GEMINI_MONSTER("Gemini Monster"),
    LINK_MONSTER("Link Monster"),
    NORMAL_MONSTER("Normal Monster"),
    NORMAL_TUNER_MONSTER("Normal Tuner Monster"),
    PENDULUM_EFFECT_FUSION_MONSTER("Pendulum Effect Fusion Monster"),
    PENDULUM_EFFECT_MONSTER("Pendulum Effect Monster"),
    PENDULUM_EFFECT_RITUAL_MONSTER("Pendulum Effect Ritual Monster"),
    PENDULUM_FLIP_EFFECT_MONSTER("Pendulum Flip Effect Monster"),
    PENDULUM_NORMAL_MONSTER("Pendulum Normal Monster"),
    PENDULUM_TUNER_EFFECT_MONSTER("Pendulum Tuner Effect Monster"),
    RITUAL_EFFECT_MONSTER("Ritual Effect Monster"),
    RITUAL_MONSTER("Ritual Monster"),
    SKILL_CARD("Skill Card"),
    SPELL_CARD("Spell Card"),
    SPIRIT_MONSTER("Spirit Monster"),
    SYNCHRO_MONSTER("Synchro Monster"),
    SYNCHRO_PENDULUM_EFFECT_MONSTER("Synchro Pendulum Effect Monster"),
    SYNCHRO_TUNER_MONSTER("Synchro Tuner Monster"),
    TOKEN("Token"),
    TOON_MONSTER("Toon Monster"),
    TRAP_CARD("Trap Card"),
    TUNER_MONSTER("Tuner Monster"),
    UNION_EFFECT_MONSTER("Union Effect Monster"),
    XYZ_MONSTER("XYZ Monster"),
    XYZ_PENDULUM_EFFECT_MONSTER("XYZ Pendulum Effect Monster")
}
