package com.example.loldex.core.model.enums

enum class RaceType(val filterName: String) {
    AQUA("Aqua"),
    BEAST("Beast"),
    BEAST_WARRIOR("Beast-Warrior"),
    CONTINUOUS("Continuous"),
    COUNTER("Counter"),
    CREATOR_GOD("Creator God"),
    CYBERSE("Cyberse"),
    DINOSAUR("Dinosaur"),
    DIVINE_BEAST("Divine-Beast"),
    DRAGON("Dragon"),
    EQUIP("Equip"),
    FAIRY("Fairy"),
    FIELD("Field"),
    FIEND("Fiend"),
    FISH("Fish"),
    ILLUSION("Illusion"),
    INSECT("Insect"),
    MACHINE("Machine"),
    NORMAL("Normal"),
    PLANT("Plant"),
    PSYCHIC("Psychic"),
    PYRO("Pyro"),
    QUICK_PLAY("Quick-Play"),
    REPTILE("Reptile"),
    RITUAL("Ritual"),
    ROCK("Rock"),
    SEA_SERPENT("Sea Serpent"),
    SPELLCASTER("Spellcaster"),
    THUNDER("Thunder"),
    WARRIOR("Warrior"),
    WINGED_BEAST("Winged Beast"),
    WYRM("Wyrm"),
    ZOMBIE("Zombie")
}